name: Binance Perp Scanner

on:
  schedule:
    - cron: "*/10 * * * *"   # 測試：每 10 分鐘跑一次
    # - cron: "0 * * * *"    # 正式：每小時跑一次
  workflow_dispatch:         # ✅ 允許手動觸發（Run workflow 會出現）

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TIMEFRAMES: ${{ secrets.TIMEFRAMES }}
          MIN_CONF: ${{ secrets.MIN_CONF }}
          RUN_LOOP: "false"
        run: python binance_perp_scanner.py